[pytest]
addopts = -v
testpaths = tests
python_files = test_*.py
python_classes = Test*
python_functions = test_*
pythonpath = .
markers =
    password_recovery: Tests for password recovery functionality
    personal_account: Tests for personal account functionality
    main_functionality: Tests for main functionality
    order_feed: Tests for order feed functionality 